# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "323e438a217f30c4d8881fe4e776ec15"
name = "HauNT Test App"
handle = "haunt-test-app-2"
application_url = "https://possible-letting-abandoned-worse.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-training-hau-nt1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_gift_cards,read_orders,read_products,write_customers,write_gift_cards,write_orders,write_products"

[auth]
redirect_urls = [
	"https://possible-letting-abandoned-worse.trycloudflare.com/auth/callback",
	"https://possible-letting-abandoned-worse.trycloudflare.com/auth/shopify/callback",
	"https://possible-letting-abandoned-worse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"
